[build]
  publish = "."
  command = "echo 'Static site deployment'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' 'unsafe-eval';"

[[redirects]]
  from = "/payment"
  to = "/pages/payment.html"
  status = 301

[[redirects]]
  from = "/services"
  to = "/pages/services.html"
  status = 301

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/pages/portfolio.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

# 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers for forms
[[headers]]
  for = "/pages/payment.html"
  [headers.values]
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"